name: Nodejs project CI Pipeline #name of the workflow

on: #to creates when workflow should run
  push: #run whenver code is pushed
    branches:
     - master #only on the "main" branch
  pull_request: # rulss on pull request targetting main branch 
    branches:
     - master


jobs: # a workflow is made of one or more jobs
  build: #name of the job 
    runs-on: ubuntu-latest # the envoironment where job will run (GITHUB-hosted runner)

    steps: # a job has multiple steps that run in order 
      - name:  checkout code #step1 :get repostitory code
        uses: actions/checkout@v3 #"uses" imports an exisiting github action

      - name: setup Node.js #step2:setup Node.js environment 
        uses: actions/setup-node@v3
        with:
          node-version: "18" #secify Node.js version 

      - name: Install dependencies # stop 3: Install npm pacakges
        run: npm install #install executes shell comands in the runner 
      
      - name: Run tests # step4 : run test cases
        run: npm test

      - name: build project #step 5: build aapplication
        run: npm run build

      - name: prepare release artifact
        run: npm ci --production && tar -czf release.tar.gz build node_modules package.json

      - name: upload artifact 
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
     - name: download artifact 
       uses: actions/download-artifact@v4
       with:
         name: release
         path: ./artifact
 
     - name: setup SSH
       run: |
          mkdir -p ~/.ssh 
          echo "${{ secrets.EC2_SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{secrets.EC2_HOST}} >> ~/.ssh/known_hosts

  -name: upload Artifact to Server
  run: |
    scp ./artifact/release.tar.gz ${{secrets.EC2_USER}}@${{secrets.EC2_HOST}}:/tmp/release.tar.gz
    ssh ${{ secrets.EC2_USER}}@${{ secrets.EC2_HOST}} <<  'EOF'
     mkdir -p ~/deploy/releases
     tar -xzf /tmp/release.tar.gz -C ~/deploy/releases
     rm /tmp/release.tar.gz
    EOF